### ISSUE TITLE
element in reduce && filter

### ISSUE THREAD

**Issue by dys2** [LambdaSchool/Testing#11]
The each in reduce and filter functions within the arrays src should take in elements instead of element because elements is being passed into the function

**Comment by invegat** [comment]
const reduce = (elements, cb, memo = elements.shift()) => {
  each(elements, (element, item) => {
    memo = cb(memo, element);
  });
  return memo;
};
const filter = (elements, cb) => {
  const filteredValues = [];
  each(elements, ((element, item) => {
    if (cb(element)) filteredValues.push(element);
  }));
  return filteredValues;
};
