### ISSUE TITLE
Callback 

### ISSUE THREAD

**Issue by Nschennum** [LambdaSchool/Testing#139]
In Array.js at line #3, the callback is being sent in as the element, and no actual callback is being sent in. There is an issue with the parenthesis in the function at line #33-35. 
Was: `each((element, item) => {
    if (cb(item)) filteredValues.push(item);
  });`
Should be: ` each(elements, item => {
    if (cb(item)) filteredValues.push(item);
  });`

**Comment by luishrd** [comment]
Thanks
