### ISSUE TITLE
each function takes two arguments, but in reduce, each is only given one argument (a callback)

### ISSUE THREAD

**Issue by lefrenk** [LambdaSchool/Testing#40]
https://github.com/LambdaSchool/Testing/blob/0a99bbd26d1e74614891e2b07f8afca10aa55d1a/advanced-javascript/src/arrays.js#L16

```
const reduce = (elements, cb, memo = elements.shift()) => {
  each((elements, item) => {
    memo = cb(memo, item)
  })
  return memo
}
```

Should be replaced with

```
const reduce = (elements, cb, memo = elements.shift()) => {
  each(elements, item => {
    memo = cb(memo, item)
  })
  return memo
}
```

**Comment by etisdew** [comment]
I know its late but I'm not seeing the issue.

**Comment by etisdew** [comment]
PR posted if they dont take it, then it is an intentional error related to the topic at hand. Does this satisfy closing the issue?

**Comment by lefrenk** [comment]
Looks good to me. Thanks for the PR :)

**Comment by perryahern** [comment]
Problem still exists - CS6 just ran into it. This code for reduce in arrays.js works and makes the linter happy:

`const reduce = (elements, cb, memo = elements.shift()) => {
  each(elements, (item) => {
    memo = cb(memo, item);
  });
  return memo;
};`

**Comment by seanchen1991** [comment]
Fixed.
